### ISSUE TITLE
how do i remove the check

### ISSUE THREAD

**Issue by floppa-the-flopper** [Chasyxx/EnBeat_NEW#5]
![image](https://github.com/Chasyxx/EnBeat_NEW/assets/142877833/2d4e50db-6b70-400d-9d10-326f1eca0554)

**Comment by Chasyxx** [comment]
This is mainly inspired by a similar thing added upstream: https://github.com/SthephanShinkufag/bytebeat-composer/issues/77 . The world need not be flooded by several unmodified clones of the website that are constantly promoted within the community. If you know what you're doing, and understand what you're trying to add, and it's actually substantial, look to [the main script](https://github.com/Chasyxx/EnBeat_NEW/blob/master/scripts/bytebeat.mjs) for answers. I'm not going to say exactly where the check is, because i don't want to make it completely useless, but this is the file. You should have a reason to fork this.

**Comment by asfaew** [comment]
i am on a diff account, i have removed the check's if statement and it did nothing

**Comment by asfaew** [comment]
i fixed it, it was also in menus.js
